sudo: true
language: c
compiler:
- clang
- gcc
install:
- sudo apt-get update
- sudo apt-get install liblog4c-dev
- wget http://launchpadlibrarian.net/291735619/libcmocka0_1.0.1-3_amd64.deb
- wget http://launchpadlibrarian.net/291735617/libcmocka-dev_1.0.1-3_amd64.deb
- sudo dpkg -i libcmocka0_1.0.1-3_amd64.deb
- sudo dpkg -i libcmocka-dev_1.0.1-3_amd64.deb
before_script:
- sudo sysctl vm.overcommit_memory=1
script:
- autoreconf -vif
- ./configure
- make check
