sudo: true
language: c
compiler:
- clang
- gcc
install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -qq; else brew update; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -qq liblog4c-dev libcmocka-dev; else brew install log4c cmocka; fi
before_script:
- if [ $TRAVIS_OS_NAME = linux ]; sudo sysctl vm.overcommit_memory=1; fi
script: ./configure && make check
