sudo: true
language: c
compiler:
- clang
- gcc
install:
- sudo apt-get update -qq
- sudo apt-get install -qq liblog4c-dev libcmocka-dev
before_script:
- sudo sysctl vm.overcommit_memory=1
script: ./configure && make check
